server:
  port: 8000
  servlet:
    context-path: /
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring?serverTimezone=Asia/Seoul
    username: shareHouse
    password: bitc5600
    driver-class-name: com.mysql.cj.jdbc.Driver 